version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: library    # Create a database named "library"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"